version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  jumpserver:
    build: .
    container_name: jumpserver
    restart: "no"
    ports:
      - 8080:8080
    depends_on:
      - redis
    volumes:
      - .:/opt/jumpserver
    environment:
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
  coco:
    image: jumpserver/coco:v0.4.0-beta1
    container_name: coco
    restart: "no"
    ports:
      - 2222:2222
    depends_on:
      - jumpserver
  luna:
    image: jumpserver/luna:v0.4.0-beta1
    container_name: luna
    restart: "no"
    ports:
      - 5000:5000
    depends_on:
      - jumpserver

